import {DatetimeInterface} from '../logic/datetime.interface';
import {Injectable, Pipe} from '@angular/core';
import * as moment from 'jalali-moment';
import {Timezones} from '../timezones.interface';

@Pipe({
  name: 'jalali'
})

@Injectable({
  providedIn: 'root',
})
export class DatetimeService {
  private weekDaysFa = ['شنبه', 'یکشنبه', 'دوشنبه', 'سه شنبه', 'چهارشنبه', 'پنجشنبه', 'جمعه'];
  private monthFa = ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'];
  private weekDaysEn = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  private datetime: DatetimeInterface;
  private todayJalali = moment().locale('fa').format('D') + ' ' + this.monthFa[moment().locale('fa').format('M')] + ' ' + moment().locale('fa').format('YYYY');
  private todayGregorian = moment().locale('en').format('D') + ' ' + moment().locale('en').format('MMMM') + ' ' + moment().locale('en').format('YYYY');
  private todayJalaliDayName = this.weekDaysFa[new Date().getDay() + 1];
  private todayGregorianDayName = this.weekDaysEn[new Date().getDay()];
  public aryIannaTimeZones: Timezones[] = [
    {city: 'Andorra', timezone: 'Europe/Andorra'},
    {city: 'Dubai', timezone: 'Asia/Dubai'},
    {city: 'Kabul', timezone: 'Asia/Kabul'},
    {city: 'Tirane', timezone: 'Europe/Tirane'},
    {city: 'Yerevan', timezone: 'Asia/Yerevan'},
    {city: 'Casey', timezone: 'Antarctica/Casey'},
    {city: 'Davis', timezone: 'Antarctica/Davis'},
    {city: 'DumontDUrville', timezone: 'Antarctica/DumontDUrville'},
    {city: 'Mawson', timezone: 'Antarctica/Mawson'},
    {city: 'Palmer', timezone: 'Antarctica/Palmer'},
    {city: 'Rothera', timezone: 'Antarctica/Rothera'},
    {city: 'Syowa', timezone: 'Antarctica/Syowa'},
    {city: 'Troll', timezone: 'Antarctica/Troll'},
    {city: 'Vostok', timezone: 'Antarctica/Vostok'},
    {city: 'Argentina', timezone: 'America/Argentina/Buenos_Aires'},
    {city: 'Argentina', timezone: 'America/Argentina/Cordoba'},
    {city: 'Argentina', timezone: 'America/Argentina/Salta'},
    {city: 'Argentina', timezone: 'America/Argentina/Jujuy'},
    {city: 'Argentina', timezone: 'America/Argentina/Tucuman'},
    {city: 'Argentina', timezone: 'America/Argentina/Catamarca'},
    {city: 'Argentina', timezone: 'America/Argentina/La_Rioja'},
    {city: 'Argentina', timezone: 'America/Argentina/San_Juan'},
    {city: 'Argentina', timezone: 'America/Argentina/Mendoza'},
    {city: 'Argentina', timezone: 'America/Argentina/San_Luis'},
    {city: 'Argentina', timezone: 'America/Argentina/Rio_Gallegos'},
    {city: 'Argentina', timezone: 'America/Argentina/Ushuaia'},
    {city: 'Pago_Pago', timezone: 'Pacific/Pago_Pago'},
    {city: 'Vienna', timezone: 'Europe/Vienna'},
    {city: 'Lord_Howe', timezone: 'Australia/Lord_Howe'},
    {city: 'Macquarie', timezone: 'Antarctica/Macquarie'},
    {city: 'Hobart', timezone: 'Australia/Hobart'},
    {city: 'Currie', timezone: 'Australia/Currie'},
    {city: 'Melbourne', timezone: 'Australia/Melbourne'},
    {city: 'Sydney', timezone: 'Australia/Sydney'},
    {city: 'Broken_Hill', timezone: 'Australia/Broken_Hill'},
    {city: 'Brisbane', timezone: 'Australia/Brisbane'},
    {city: 'Lindeman', timezone: 'Australia/Lindeman'},
    {city: 'Adelaide', timezone: 'Australia/Adelaide'},
    {city: 'Darwin', timezone: 'Australia/Darwin'},
    {city: 'Perth', timezone: 'Australia/Perth'},
    {city: 'Eucla', timezone: 'Australia/Eucla'},
    {city: 'Baku', timezone: 'Asia/Baku'},
    {city: 'Barbados', timezone: 'America/Barbados'},
    {city: 'Dhaka', timezone: 'Asia/Dhaka'},
    {city: 'Brussels', timezone: 'Europe/Brussels'},
    {city: 'Sofia', timezone: 'Europe/Sofia'},
    {city: 'Bermuda', timezone: 'Atlantic/Bermuda'},
    {city: 'Brunei', timezone: 'Asia/Brunei'},
    {city: 'La_Paz', timezone: 'America/La_Paz'},
    {city: 'Noronha', timezone: 'America/Noronha'},
    {city: 'Belem', timezone: 'America/Belem'},
    {city: 'Fortaleza', timezone: 'America/Fortaleza'},
    {city: 'Recife', timezone: 'America/Recife'},
    {city: 'Araguaina', timezone: 'America/Araguaina'},
    {city: 'Maceio', timezone: 'America/Maceio'},
    {city: 'Bahia', timezone: 'America/Bahia'},
    {city: 'Sao_Paulo', timezone: 'America/Sao_Paulo'},
    {city: 'Campo_Grande', timezone: 'America/Campo_Grande'},
    {city: 'Cuiaba', timezone: 'America/Cuiaba'},
    {city: 'Santarem', timezone: 'America/Santarem'},
    {city: 'Porto_Velho', timezone: 'America/Porto_Velho'},
    {city: 'Boa_Vista', timezone: 'America/Boa_Vista'},
    {city: 'Manaus', timezone: 'America/Manaus'},
    {city: 'Eirunepe', timezone: 'America/Eirunepe'},
    {city: 'Rio_Branco', timezone: 'America/Rio_Branco'},
    {city: 'Nassau', timezone: 'America/Nassau'},
    {city: 'Thimphu', timezone: 'Asia/Thimphu'},
    {city: 'Minsk', timezone: 'Europe/Minsk'},
    {city: 'Belize', timezone: 'America/Belize'},
    {city: 'St_Johns', timezone: 'America/St_Johns'},
    {city: 'Halifax', timezone: 'America/Halifax'},
    {city: 'Glace_Bay', timezone: 'America/Glace_Bay'},
    {city: 'Moncton', timezone: 'America/Moncton'},
    {city: 'Goose_Bay', timezone: 'America/Goose_Bay'},
    {city: 'Blanc', timezone: 'America/Blanc-Sablon'},
    {city: 'Toronto', timezone: 'America/Toronto'},
    {city: 'Nipigon', timezone: 'America/Nipigon'},
    {city: 'Thunder_Bay', timezone: 'America/Thunder_Bay'},
    {city: 'Iqaluit', timezone: 'America/Iqaluit'},
    {city: 'Pangnirtung', timezone: 'America/Pangnirtung'},
    {city: 'Atikokan', timezone: 'America/Atikokan'},
    {city: 'Winnipeg', timezone: 'America/Winnipeg'},
    {city: 'Rainy_River', timezone: 'America/Rainy_River'},
    {city: 'Resolute', timezone: 'America/Resolute'},
    {city: 'Rankin_Inlet', timezone: 'America/Rankin_Inlet'},
    {city: 'Regina', timezone: 'America/Regina'},
    {city: 'Swift_Current', timezone: 'America/Swift_Current'},
    {city: 'Edmonton', timezone: 'America/Edmonton'},
    {city: 'Cambridge_Bay', timezone: 'America/Cambridge_Bay'},
    {city: 'Yellowknife', timezone: 'America/Yellowknife'},
    {city: 'Inuvik', timezone: 'America/Inuvik'},
    {city: 'Creston', timezone: 'America/Creston'},
    {city: 'Dawson_Creek', timezone: 'America/Dawson_Creek'},
    {city: 'Fort_Nelson', timezone: 'America/Fort_Nelson'},
    {city: 'Vancouver', timezone: 'America/Vancouver'},
    {city: 'Whitehorse', timezone: 'America/Whitehorse'},
    {city: 'Dawson', timezone: 'America/Dawson'},
    {city: 'Cocos', timezone: 'Indian/Cocos'},
    {city: 'Zurich', timezone: 'Europe/Zurich'},
    {city: 'Abidjan', timezone: 'Africa/Abidjan'},
    {city: 'Rarotonga', timezone: 'Pacific/Rarotonga'},
    {city: 'Santiago', timezone: 'America/Santiago'},
    {city: 'Punta_Arenas', timezone: 'America/Punta_Arenas'},
    {city: 'Easter', timezone: 'Pacific/Easter'},
    {city: 'Shanghai', timezone: 'Asia/Shanghai'},
    {city: 'Urumqi', timezone: 'Asia/Urumqi'},
    {city: 'Bogota', timezone: 'America/Bogota'},
    {city: 'Costa_Rica', timezone: 'America/Costa_Rica'},
    {city: 'Havana', timezone: 'America/Havana'},
    {city: 'Cape_Verde', timezone: 'Atlantic/Cape_Verde'},
    {city: 'Curacao', timezone: 'America/Curacao'},
    {city: 'Christmas', timezone: 'Indian/Christmas'},
    {city: 'Nicosia', timezone: 'Asia/Nicosia'},
    {city: 'Famagusta', timezone: 'Asia/Famagusta'},
    {city: 'Prague', timezone: 'Europe/Prague'},
    {city: 'Berlin', timezone: 'Europe/Berlin'},
    {city: 'Copenhagen', timezone: 'Europe/Copenhagen'},
    {city: 'Santo_Domingo', timezone: 'America/Santo_Domingo'},
    {city: 'Algiers', timezone: 'Africa/Algiers'},
    {city: 'Guayaquil', timezone: 'America/Guayaquil'},
    {city: 'Galapagos', timezone: 'Pacific/Galapagos'},
    {city: 'Tallinn', timezone: 'Europe/Tallinn'},
    {city: 'Cairo', timezone: 'Africa/Cairo'},
    {city: 'El_Aaiun', timezone: 'Africa/El_Aaiun'},
    {city: 'Madrid', timezone: 'Europe/Madrid'},
    {city: 'Ceuta', timezone: 'Africa/Ceuta'},
    {city: 'Canary', timezone: 'Atlantic/Canary'},
    {city: 'Helsinki', timezone: 'Europe/Helsinki'},
    {city: 'Fiji', timezone: 'Pacific/Fiji'},
    {city: 'Stanley', timezone: 'Atlantic/Stanley'},
    {city: 'Chuuk', timezone: 'Pacific/Chuuk'},
    {city: 'Pohnpei', timezone: 'Pacific/Pohnpei'},
    {city: 'Kosrae', timezone: 'Pacific/Kosrae'},
    {city: 'Faroe', timezone: 'Atlantic/Faroe'},
    {city: 'Paris', timezone: 'Europe/Paris'},
    {city: 'London', timezone: 'Europe/London'},
    {city: 'Tbilisi', timezone: 'Asia/Tbilisi'},
    {city: 'Cayenne', timezone: 'America/Cayenne'},
    {city: 'Accra', timezone: 'Africa/Accra'},
    {city: 'Gibraltar', timezone: 'Europe/Gibraltar'},
    {city: 'Godthab', timezone: 'America/Godthab'},
    {city: 'Danmarkshavn', timezone: 'America/Danmarkshavn'},
    {city: 'Scoresbysund', timezone: 'America/Scoresbysund'},
    {city: 'Thule', timezone: 'America/Thule'},
    {city: 'Athens', timezone: 'Europe/Athens'},
    {city: 'South_Georgia', timezone: 'Atlantic/South_Georgia'},
    {city: 'Guatemala', timezone: 'America/Guatemala'},
    {city: 'Guam', timezone: 'Pacific/Guam'},
    {city: 'Bissau', timezone: 'Africa/Bissau'},
    {city: 'Guyana', timezone: 'America/Guyana'},
    {city: 'Hong_Kong', timezone: 'Asia/Hong_Kong'},
    {city: 'Tegucigalpa', timezone: 'America/Tegucigalpa'},
    {city: 'Port', timezone: 'America/Port-a}u-Prince'},
    {city: 'Budapest', timezone: 'Europe/Budapest'},
    {city: 'Jakarta', timezone: 'Asia/Jakarta'},
    {city: 'Pontianak', timezone: 'Asia/Pontianak'},
    {city: 'Makassar', timezone: 'Asia/Makassar'},
    {city: 'Jayapura', timezone: 'Asia/Jayapura'},
    {city: 'Dublin', timezone: 'Europe/Dublin'},
    {city: 'Jerusalem', timezone: 'Asia/Jerusalem'},
    {city: 'Kolkata', timezone: 'Asia/Kolkata'},
    {city: 'Chagos', timezone: 'Indian/Chagos'},
    {city: 'Baghdad', timezone: 'Asia/Baghdad'},
    {city: 'Reykjavik', timezone: 'Atlantic/Reykjavik'},
    {city: 'Rome', timezone: 'Europe/Rome'},
    {city: 'Jamaica', timezone: 'America/Jamaica'},
    {city: 'Amman', timezone: 'Asia/Amman'},
    {city: 'Tokyo', timezone: 'Asia/Tokyo'},
    {city: 'Nairobi', timezone: 'Africa/Nairobi'},
    {city: 'Bishkek', timezone: 'Asia/Bishkek'},
    {city: 'Tarawa', timezone: 'Pacific/Tarawa'},
    {city: 'Enderbury', timezone: 'Pacific/Enderbury'},
    {city: 'Kiritimati', timezone: 'Pacific/Kiritimati'},
    {city: 'Pyongyang', timezone: 'Asia/Pyongyang'},
    {city: 'Seoul', timezone: 'Asia/Seoul'},
    {city: 'Almaty', timezone: 'Asia/Almaty'},
    {city: 'Qyzylorda', timezone: 'Asia/Qyzylorda'},
    {city: 'Qostanay', timezone: 'Asia/Qostanay'},
    {city: 'Aqtobe', timezone: 'Asia/Aqtobe'},
    {city: 'Aqtau', timezone: 'Asia/Aqtau'},
    {city: 'Atyrau', timezone: 'Asia/Atyrau'},
    {city: 'Oral', timezone: 'Asia/Oral'},
    {city: 'Beirut', timezone: 'Asia/Beirut'},
    {city: 'Colombo', timezone: 'Asia/Colombo'},
    {city: 'Monrovia', timezone: 'Africa/Monrovia'},
    {city: 'Vilnius', timezone: 'Europe/Vilnius'},
    {city: 'Luxembourg', timezone: 'Europe/Luxembourg'},
    {city: 'Riga', timezone: 'Europe/Riga'},
    {city: 'Tripoli', timezone: 'Africa/Tripoli'},
    {city: 'Casablanca', timezone: 'Africa/Casablanca'},
    {city: 'Monaco', timezone: 'Europe/Monaco'},
    {city: 'Chisinau', timezone: 'Europe/Chisinau'},
    {city: 'Majuro', timezone: 'Pacific/Majuro'},
    {city: 'Kwajalein', timezone: 'Pacific/Kwajalein'},
    {city: 'Yangon', timezone: 'Asia/Yangon'},
    {city: 'Ulaanbaatar', timezone: 'Asia/Ulaanbaatar'},
    {city: 'Hovd', timezone: 'Asia/Hovd'},
    {city: 'Choibalsan', timezone: 'Asia/Choibalsan'},
    {city: 'Macau', timezone: 'Asia/Macau'},
    {city: 'Martinique', timezone: 'America/Martinique'},
    {city: 'Malta', timezone: 'Europe/Malta'},
    {city: 'Mauritius', timezone: 'Indian/Mauritius'},
    {city: 'Maldives', timezone: 'Indian/Maldives'},
    {city: 'Mexico_City', timezone: 'America/Mexico_City'},
    {city: 'Cancun', timezone: 'America/Cancun'},
    {city: 'Merida', timezone: 'America/Merida'},
    {city: 'Monterrey', timezone: 'America/Monterrey'},
    {city: 'Matamoros', timezone: 'America/Matamoros'},
    {city: 'Mazatlan', timezone: 'America/Mazatlan'},
    {city: 'Chihuahua', timezone: 'America/Chihuahua'},
    {city: 'Ojinaga', timezone: 'America/Ojinaga'},
    {city: 'Hermosillo', timezone: 'America/Hermosillo'},
    {city: 'Tijuana', timezone: 'America/Tijuana'},
    {city: 'Bahia_Banderas', timezone: 'America/Bahia_Banderas'},
    {city: 'Kuala_Lumpur', timezone: 'Asia/Kuala_Lumpur'},
    {city: 'Kuching', timezone: 'Asia/Kuching'},
    {city: 'Maputo', timezone: 'Africa/Maputo'},
    {city: 'Windhoek', timezone: 'Africa/Windhoek'},
    {city: 'Noumea', timezone: 'Pacific/Noumea'},
    {city: 'Norfolk', timezone: 'Pacific/Norfolk'},
    {city: 'Lagos', timezone: 'Africa/Lagos'},
    {city: 'Managua', timezone: 'America/Managua'},
    {city: 'Amsterdam', timezone: 'Europe/Amsterdam'},
    {city: 'Oslo', timezone: 'Europe/Oslo'},
    {city: 'Kathmandu', timezone: 'Asia/Kathmandu'},
    {city: 'Nauru', timezone: 'Pacific/Nauru'},
    {city: 'Niue', timezone: 'Pacific/Niue'},
    {city: 'Auckland', timezone: 'Pacific/Auckland'},
    {city: 'Chatham', timezone: 'Pacific/Chatham'},
    {city: 'Panama', timezone: 'America/Panama'},
    {city: 'Lima', timezone: 'America/Lima'},
    {city: 'Tahiti', timezone: 'Pacific/Tahiti'},
    {city: 'Marquesas', timezone: 'Pacific/Marquesas'},
    {city: 'Gambier', timezone: 'Pacific/Gambier'},
    {city: 'Port_Moresby', timezone: 'Pacific/Port_Moresby'},
    {city: 'Bougainville', timezone: 'Pacific/Bougainville'},
    {city: 'Manila', timezone: 'Asia/Manila'},
    {city: 'Karachi', timezone: 'Asia/Karachi'},
    {city: 'Warsaw', timezone: 'Europe/Warsaw'},
    {city: 'Miquelon', timezone: 'America/Miquelon'},
    {city: 'Pitcairn', timezone: 'Pacific/Pitcairn'},
    {city: 'Puerto_Rico', timezone: 'America/Puerto_Rico'},
    {city: 'Gaza', timezone: 'Asia/Gaza'},
    {city: 'Hebron', timezone: 'Asia/Hebron'},
    {city: 'Lisbon', timezone: 'Europe/Lisbon'},
    {city: 'Madeira', timezone: 'Atlantic/Madeira'},
    {city: 'Azores', timezone: 'Atlantic/Azores'},
    {city: 'Palau', timezone: 'Pacific/Palau'},
    {city: 'Asuncion', timezone: 'America/Asuncion'},
    {city: 'Qatar', timezone: 'Asia/Qatar'},
    {city: 'Reunion', timezone: 'Indian/Reunion'},
    {city: 'Bucharest', timezone: 'Europe/Bucharest'},
    {city: 'Belgrade', timezone: 'Europe/Belgrade'},
    {city: 'Kaliningrad', timezone: 'Europe/Kaliningrad'},
    {city: 'Moscow', timezone: 'Europe/Moscow'},
    {city: 'Simferopol', timezone: 'Europe/Simferopol'},
    {city: 'Kirov', timezone: 'Europe/Kirov'},
    {city: 'Astrakhan', timezone: 'Europe/Astrakhan'},
    {city: 'Volgograd', timezone: 'Europe/Volgograd'},
    {city: 'Saratov', timezone: 'Europe/Saratov'},
    {city: 'Ulyanovsk', timezone: 'Europe/Ulyanovsk'},
    {city: 'Samara', timezone: 'Europe/Samara'},
    {city: 'Yekaterinburg', timezone: 'Asia/Yekaterinburg'},
    {city: 'Omsk', timezone: 'Asia/Omsk'},
    {city: 'Novosibirsk', timezone: 'Asia/Novosibirsk'},
    {city: 'Barnaul', timezone: 'Asia/Barnaul'},
    {city: 'Tomsk', timezone: 'Asia/Tomsk'},
    {city: 'Novokuznetsk', timezone: 'Asia/Novokuznetsk'},
    {city: 'Krasnoyarsk', timezone: 'Asia/Krasnoyarsk'},
    {city: 'Irkutsk', timezone: 'Asia/Irkutsk'},
    {city: 'Chita', timezone: 'Asia/Chita'},
    {city: 'Yakutsk', timezone: 'Asia/Yakutsk'},
    {city: 'Khandyga', timezone: 'Asia/Khandyga'},
    {city: 'Vladivostok', timezone: 'Asia/Vladivostok'},
    {city: 'Ust', timezone: 'Asia/Ust-Nera'},
    {city: 'Magadan', timezone: 'Asia/Magadan'},
    {city: 'Sakhalin', timezone: 'Asia/Sakhalin'},
    {city: 'Srednekolymsk', timezone: 'Asia/Srednekolymsk'},
    {city: 'Kamchatka', timezone: 'Asia/Kamchatka'},
    {city: 'Anadyr', timezone: 'Asia/Anadyr'},
    {city: 'Riyadh', timezone: 'Asia/Riyadh'},
    {city: 'Guadalcanal', timezone: 'Pacific/Guadalcanal'},
    {city: 'Mahe', timezone: 'Indian/Mahe'},
    {city: 'Khartoum', timezone: 'Africa/Khartoum'},
    {city: 'Stockholm', timezone: 'Europe/Stockholm'},
    {city: 'Singapore', timezone: 'Asia/Singapore'},
    {city: 'Paramaribo', timezone: 'America/Paramaribo'},
    {city: 'Juba', timezone: 'Africa/Juba'},
    {city: 'Sao_Tome', timezone: 'Africa/Sao_Tome'},
    {city: 'El_Salvador', timezone: 'America/El_Salvador'},
    {city: 'Damascus', timezone: 'Asia/Damascus'},
    {city: 'Grand_Turk', timezone: 'America/Grand_Turk'},
    {city: 'Ndjamena', timezone: 'Africa/Ndjamena'},
    {city: 'Kerguelen', timezone: 'Indian/Kerguelen'},
    {city: 'Bangkok', timezone: 'Asia/Bangkok'},
    {city: 'Dushanbe', timezone: 'Asia/Dushanbe'},
    {city: 'Fakaofo', timezone: 'Pacific/Fakaofo'},
    {city: 'Dili', timezone: 'Asia/Dili'},
    {city: 'Ashgabat', timezone: 'Asia/Ashgabat'},
    {city: 'Tunis', timezone: 'Africa/Tunis'},
    {city: 'Tongatapu', timezone: 'Pacific/Tongatapu'},
    {city: 'Istanbul', timezone: 'Europe/Istanbul'},
    {city: 'Port_of_Spain', timezone: 'America/Port_of_Spain'},
    {city: 'Funafuti', timezone: 'Pacific/Funafuti'},
    {city: 'Taipei', timezone: 'Asia/Taipei'},
    {city: 'Kiev', timezone: 'Europe/Kiev'},
    {city: 'Uzhgorod', timezone: 'Europe/Uzhgorod'},
    {city: 'Zaporozhye', timezone: 'Europe/Zaporozhye'},
    {city: 'Wake', timezone: 'Pacific/Wake'},
    {city: 'New_York', timezone: 'America/New_York'},
    {city: 'Detroit', timezone: 'America/Detroit'},
    {city: 'Kentucky', timezone: 'America/Kentucky/Louisville'},
    {city: 'Kentucky', timezone: 'America/Kentucky/Monticello'},
    {city: 'Indiana', timezone: 'America/Indiana/Indianapolis'},
    {city: 'Indiana', timezone: 'America/Indiana/Vincennes'},
    {city: 'Indiana', timezone: 'America/Indiana/Winamac'},
    {city: 'Indiana', timezone: 'America/Indiana/Marengo'},
    {city: 'Indiana', timezone: 'America/Indiana/Petersburg'},
    {city: 'Indiana', timezone: 'America/Indiana/Vevay'},
    {city: 'Chicago', timezone: 'America/Chicago'},
    {city: 'Indiana', timezone: 'America/Indiana/Tell_City'},
    {city: 'Indiana', timezone: 'America/Indiana/Knox'},
    {city: 'Menominee', timezone: 'America/Menominee'},
    {city: 'North_Dakota', timezone: 'America/North_Dakota/Center'},
    {city: 'North_Dakota', timezone: 'America/North_Dakota/New_Salem'},
    {city: 'North_Dakota', timezone: 'America/North_Dakota/Beulah'},
    {city: 'Denver', timezone: 'America/Denver'},
    {city: 'Boise', timezone: 'America/Boise'},
    {city: 'Phoenix', timezone: 'America/Phoenix'},
    {city: 'Los_Angeles', timezone: 'America/Los_Angeles'},
    {city: 'Anchorage', timezone: 'America/Anchorage'},
    {city: 'Juneau', timezone: 'America/Juneau'},
    {city: 'Sitka', timezone: 'America/Sitka'},
    {city: 'Metlakatla', timezone: 'America/Metlakatla'},
    {city: 'Yakutat', timezone: 'America/Yakutat'},
    {city: 'Nome', timezone: 'America/Nome'},
    {city: 'Adak', timezone: 'America/Adak'},
    {city: 'Honolulu', timezone: 'Pacific/Honolulu'},
    {city: 'Montevideo', timezone: 'America/Montevideo'},
    {city: 'Samarkand', timezone: 'Asia/Samarkand'},
    {city: 'Tashkent', timezone: 'Asia/Tashkent'},
    {city: 'Caracas', timezone: 'America/Caracas'},
    {city: 'Ho_Chi_Minh', timezone: 'Asia/Ho_Chi_Minh'},
    {city: 'Efate', timezone: 'Pacific/Efate'},
    {city: 'Wallis', timezone: 'Pacific/Wallis'},
    {city: 'Apia', timezone: 'Pacific/Apia'},
    {city: 'Johannesburg', timezone: 'Africa/Johannesburg'}
  ];

  changeDatetimeLabel(rtlDirection: boolean) {
    if (rtlDirection) {
      this.datetime = {
        time: '15:30',
        date: this.todayJalali,
        weekday: this.todayJalaliDayName
      }
    } else {
      this.datetime = {
        time: '15:30',
        date: this.todayGregorian,
        weekday: this.todayGregorianDayName
      }
    }

    return this.datetime;
  }
}
